- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: 64943e86417774b9d6ba63c74e00f8cc3e2119e0
  hooks:
   - id: autopep8-wrapper
     args: ['-i', '--max-line-length=110']
   - id: debug-statements
   - id: end-of-file-fixer
   - id: flake8
   - id: trailing-whitespace
- repo: https://github.com/openstack/bandit
  sha: 0.17.0
  hooks:
   - id: github-openstack-bandit
